### ISSUE TITLE
Iterate Neutralino.storage items

### ISSUE THREAD

**Issue by rndme** [neutralinojs/roadmap#12]
A way to simply list stored keys, or iterate key:value pairs, or perhaps get entries would be useful. I realize the filesystem's `.storage` directory can be used, but that seems hacky and potentially brittle with FS/OS complications. A higher-level API endpoint would enable cleaner and more robust application code.

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting this great idea. I think we can add this one too with the next release :tada:

**Comment by shalithasuranga** [comment]
This was added. We'll release it soon with the next release. Thanks for this nice idea @rndme  :tada:
