### ISSUE TITLE
Any plans of adding keyboard shortcuts?

### ISSUE THREAD

**Issue by ahmetsulek** [neutralinojs/roadmap#2]

**Comment by shalithasuranga** [comment]
Hey. Thanks for the idea.. you meaning global shortcuts right? Otherwise we can use`document.addEventListener('keyup'` I think or something like https://github.com/jaywcjlove/hotkeys

**Comment by zvikasdongre** [comment]
Yes please tell when will the global shortcuts will be implemented.

**Comment by danidre14** [comment]
Global shortcuts such as F11 for full screen toggle.

Additionally, when I request fullscreen on an element, my webview does not get full screened. I usually have to add an event listener and hook it up with Neu:

```javascript
document.onfullscreenchange = document.onmozfullscreenchange = document.onwebkitfullscreenchange = async function () {
    if (document.fullscreenElement !== null)
        await Neutralino.window.setFullScreen();
    else
        await Neutralino.window.exitFullScreen();
};
```

**Comment by shalithasuranga** [comment]
Hey.. this feature is added to the roadmap https://github.com/neutralinojs/roadmap
Thanks for reporting and discussing this
