### ISSUE TITLE
Adding a loading animation to the client

### ISSUE THREAD

**Issue by FrancXPT** [neutralinojs/roadmap#5]
Can we have a loading animation in the client

**Comment by FrancXPT** [comment]
thanks for the reply

**Comment by shalithasuranga** [comment]
Hey.. ah seems like you've mentioned some native animation to indicate the webview page is loading like the usual browser tab's loading animation.  Seems like this is a feature request, so I am moving this to the framework rep. Thank you very much for the idea.

**Comment by shalithasuranga** [comment]
Added: https://github.com/neutralinojs/neutralinojs/issues/814 to track this.. Thanks for the idea :)

**Comment by FrancXPT** [comment]
No problem, thanks for your support.
