### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by diverdm** [neutralinojs/roadmap#6]
If "neutralino.config.json" contains cyrillic symbols in "modes/window/title" - there is non-readable symbols in window's header. 
If cyrillic symbols in "cli/binaryName", app builds, but crashes on start
![1](https://user-images.githubusercontent.com/18134208/156144379-80acd851-bb25-48c6-9f09-4ec69ac54b92.jpg)
![2](https://user-images.githubusercontent.com/18134208/156144400-0b0634b1-3de5-4e02-8c49-a3e7388c72ae.jpg)
.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this issue. We need to fix this UTF8 issue with https://github.com/neutralinojs/neutralinojs/issues/613

**Comment by shalithasuranga** [comment]
Closing this issue since now Neutralinojs supports Unicode on Windows. Thanks :)
